module.exports = [
    { id: 'light', name: '🌝  Light' },
    { id: 'dark', name: '🌚  Dark' },
    { id: 'cupcake', name: '🧁  Cupcake' },
    { id: 'bumblebee', name: '🐝  Bumblebee' },
    { id: 'emerald', name: '✳️  Emerald' },
    { id: 'corporate', name: '🏢  Corporate' },
    { id: 'synthwave', name: '🌃  Synthwave' },
    { id: 'retro', name: '👴  Retro' },
    { id: 'cyberpunk', name: '🤖  Cyberpunk' },
    { id: 'valentine', name: '🌸  Valentine' },
    { id: 'halloween', name: '🎃  Halloween' },
    { id: 'garden', name: '🌷  Garden' },
    { id: 'forest', name: '🌲  Forest' },
    { id: 'aqua', name: '🐟  Aqua' },
    { id: 'lofi', name: '👓  Lofi' },
    { id: 'pastel', name: '🖍  Pastel' },
    { id: 'fantasy', name: '🧚‍♀️  Fantasy' },
    { id: 'wireframe', name: '📝  Wireframe' },
    { id: 'black', name: '🏴  Black' },
    { id: 'luxury', name: '💎  Luxury' },
    { id: 'dracula', name: '🧛‍♂️  Dracula' },
];
